#!/bin/bash

curl https://raw.githubusercontent.com/horta/zstd.install/master/install --output install-zstd
bash install-zstd

curl -fsSL https://git.io/JerYI | GITHUB_USER=horta GITHUB_PROJECT=almosthere bash
curl -fsSL https://git.io/JerYI | GITHUB_USER=limix GITHUB_PROJECT=bgen bash
