#!/bin/bash

cp /c/Windows/system32/athr.dll bgen_reader/
cp /c/Windows/system32/bgen.dll bgen_reader/
cp /c/Windows/system32/zlib.dll bgen_reader/
cp /c/Windows/system32/libzstd.dll bgen_reader/

pwd
ls bgen_reader/
