name: 🧪 Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: |
          pipx run poetry install
          pipx run poetry run pytest
